config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /usrs/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# ユーザー
  scope module: :public do
    # homes
    root to: "homes#top"
    get "/privacy"=>"homes#privacy",as: 'privacy'
    get "/help"=>"homes#help",as: 'help'

    # users
    get "/users/my_page"=>"users#my_page",as: 'my_page'
    get "/users/unsubscribe"=>"users#unsubscribe",as: 'unsubscribe'
    patch "/users/withdraw"=>"users#withdraw"
    resources :users, only: [:index, :show, :update, :edit] do
      # relationships
      resource :relationships, only: [:create, :destroy, :follower]
      get "/relationships/following"=>"relationships#following",as: 'following'
      get "/relationships/follower"=>"relationships#follower",as: 'follower'
      # reports
      resources :reports, only: [:new, :create]
    end
    get 'users/:id/reports' => redirect("/users/%{id}/reports/new")
    
    # posts
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      # bookmarks
      resource :bookmarks, only: [:create, :destroy]
      get "/bookmarks/favorite"=>"bookmarks#favorite",as: 'favorite'
    end
    
    # comments
    resources :comments, only: [:create, :destroy]

  end

# 管理者
  namespace :admin do
    root to: "users#index"
  # posts
    resources :posts, only: [:index, :show, :destroy]
  # users
    resources :users, only: [:show, :edit, :update]
  # reports
    resources :reports, only: [:index, :show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  attribute :current_tags       # current_tagsというカラムを作成
# user
  belongs_to :user
# post_tags
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags, dependent: :destroy
# bookmark
  has_many :bookmarks, dependent: :destroy
# comment
  has_many :comments, dependent: :destroy

  validates :introduction, presence: true, length: { minimum: 3 }

  scope :with_out_is_deleted, -> {includes(:user).where(user: {is_deleted: false})}

  before_validation :split_text
  after_save :save_tags
  after_initialize :append_tags, unless: :new_record?

  def split_text
    unless self.introduction == ""
      data = self.introduction.split("#")     #新規投稿でのデータで、タグを表す # のもつデータを配列で、投稿文と分ける
      self.introduction = data.shift.chomp
      self.current_tags = data                #タグをcurrent_tagsへ
    end
  end

  # タグの保存
  def save_tags
    unless self.introduction == ""
      posted_tags = self.current_tags.map{|tag| Tag.find_or_create_by(name: tag) }      #新規投稿時のタグが新しいものか既にあるものかを判別する
      recorded_tags = self.tags                           #新規投稿時に判別されたタグ
      new_tags = posted_tags - recorded_tags              #26と27行目で新しいタグかを判別
      old_tags = recorded_tags - posted_tags              #26と27行目で既にあるタグかを判別
      # 新しいタグの場合
      new_tags.each do |tag|
        self.post_tags.create!(tag_id: tag.id)
      end
      # 既に保存されているタグの場合
      old_tags.each do |tag|
        count = tag.post_tags.size
        if count <= 1
          tag.destroy
        else
          post_tag = self.post_tags.find_by(tag_id: tag.id)
          post_tag.destroy if post_tag
        end
      end
    end
  end

  # 編集する際にフォームにタグを表示させる
  def append_tags
    if self.introduction.present? && self.tags.present?
      recorded_tags = "\r\n#" + self.tags.pluck(:name).join(' #')
      self.introduction = self.introduction + recorded_tags
    end
  end

# 既にブックマークしているかを検証します
  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end

# 投稿画像(複数)
  has_many_attached :images
  validate :image_length

  def get_image(image, width, height)
    image.variant(resize_to_limit: [width, height]).processed
  end

  private

  def image_length
    if images.length > 5
      errors.add(:images, "　投稿画像は5枚以内にしてください。")
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
# 管理者側  投稿
  before_action :authenticate_admin!
  
  def index
    @posts = Post.all
    # 検索機能
    if admin_signed_in?
      if params[:search].present?             # 検索のフォームに何か検索ワードが入っていたら
        # 投稿のタグから探す
        tag_posts = @posts.joins(:tags).distinct.where('tags.name like ?', "%#{params[:search]}%")
        # 投稿者、投稿ID、投稿場所を探す
        posts = @posts.joins(:user).where('posts.id like ?', "%#{params[:search]}%").or(
                @posts.joins(:user).where('posts.name like ?', "%#{params[:search]}%")).or(
                @posts.joins(:user).where('users.id like ?', "%#{params[:search]}%")).or(
                @posts.joins(:user).where('users.first_name like ?', "%#{params[:search]}%")).or(
                @posts.joins(:user).where('users.last_name like ?', "%#{params[:search]}%")).or(
                @posts.joins(:user).where('users.user_name like ?', "%#{params[:search]}%"))
        # tag_posts と posts で重複しないように uniq を設定
        @posts = (tag_posts + posts).uniq
      end
    end
    # 検索結果がなかった場合
    if params[:search].present? && @posts.count == 0
      flash[:alert] = "検索結果がありません"
      render :index
    end
    flash[:alert] = nil
  end
  
  def show
    @post = Post.find(params[:id])
    @post.split_text
    @user = @post.user
    # コメント機能
    @comments = @post.comments.page(params[:page])          #投稿詳細に関連付けてあるコメントを全て取得
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "投稿削除完了"
    redirect_to admin_posts_path
  end
  
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_showedCal.html.erb
<div class="container">

　<!--投稿者-->
  <div class="row">

    <div class="col-md-12 post-show">
      <div class="col-md-8 col-lg-6 text-center mx-auto">
        <table class="table table-sm">
          <tr>　<!--プロフィール画像-->
            <td class="text-center">
              <%= image_tag user.get_profile_image(60,60), class: "profile_image", style: "height: 70px; width: 70px;" %>
            </td>
            <td class="post-user-name py-4">
              <h5>　<!--ユーザーネーム-->
                <% if admin_signed_in? %>
                  <%= link_to user.user_name, admin_user_path(user.id) %>
                <% else %>
                  <%= link_to user.user_name, user_path(user.id) %>
                <% end %>
              </h5>
            </td>
          </tr>
        </table>
      </div>

      <div class="col-md-9 col-lg-6 text-center mx-auto">
        <!--投稿画像-->
        <% if post.images.attached? %>
        <!--カルーセル-->
          <div id="carousel" class="carousel slide" data-ride="carousel">
            <!-- カルーセルインジケーター -->
            <ol class="carousel-indicators">
              <% post.images.each_with_index do |image, idx| %>
                <% if idx == 0 %>
                  <li data-target="#carousel" data-slide-to="0" class="active"></li>
                <% else %>
                  <li data-target="#carousel" data-slide-to="<%= idx %>"></li>
                <% end %>
              <% end %>
            </ol>
            <!-- 画像 -->
            <div class="carousel-inner text-center">
              <% post.images.each_with_index do |image, idx| %>
                <% if idx == 0 %>
                  <div class="carousel-item active">
                    <%= image_tag post.get_image(image, 600,400), style: 'width: 80%; height: 300px; object-fit: cover;' %>
                  </div>
                <% else %>
                  <div class="carousel-item">
                    <%= image_tag post.get_image(image, 600,400), style: 'width: 80%; height: 300px; object-fit: cover;' %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <!-- カルーセルコントローラー -->
            <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        <% else %>
          <div class="d-flex justify-content-center">
            <%= image_tag asset_path('no_image.jpg'),width: 200, height: 190 %>
          </div>
        <% end %>
        
        <!--ユーザーがログインしている場合に編集、削除リンクを表示-->
        <% if user_signed_in? %>
          <div class="my-4 text-center">
            <% if post.user_id == current_user.id %>
              <!--編集リンク & Font Awesome-->
              <%= link_to edit_post_path(post.id), class: "mr-5" do %>
                <i class="fa-regular fa-pen-to-square" style="font-size:30px; color:#111;"></i>
              <% end %>
              <!--削除リンク & Font Awesome-->
              <%= link_to post_path(post), method: :delete, class: "ml-5", "data-confirm" => "本当に削除しますか？" do %>
                <i class="far fa-trash-alt" style="font-size:30px; color:red;"></i>
              <% end %>
            <% else %>
            <% end %>
          </div>
        <% end %>
      </div>
      
      <!--投稿情報-->
      <div class="col-md-9 col-lg-8 mt-3 text-center mx-auto">
        <table class="table table-border">
          <tr class="row">
            <td class="col-3">投稿日</td>
            <td class="col-9"><%= post.created_at.strftime("%Y/%m/%d") %></td>
          </tr>
          <tr class="row">
            <td class="col-3">名称</td>
            <td class="col-9"><strong><%= post.name %></strong></td>
          </tr>
          <tr class="row border-bottom">
            <td class="col-3">住所</td>
            <td class="col-9"><%= post.address %></td>
          </tr>
        </table>

        <!--タグのリンク一覧表示(リンク先はそのタグが検索された状態の一覧画面)-->
        <% if post.tags.present? %>
          <p class="d-inline"><strong>タグ：</strong></p>
          <% post.tags.each do |post| %>
            <% if admin_signed_in? %>
              <%= link_to post.name, admin_posts_path(search: post.name), 'data-turbolinks': false, class: "badge rounded-pill bg-secondary", style: "color:#fff;" %>
            <% else %>
              <%= link_to post.name, posts_path(search: post.name), 'data-turbolinks': false, class: "badge rounded-pill bg-secondary", style: "color:#fff;" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-12">
      <div class="col-12 col-md-9 col-lg-8 mt-2 text-center mx-auto">
        <!--ブックマーク機能-->
        <% if user_signed_in? %>
          <div class="mb-2 d-flex justify-content-center bookmark-link">
            <% if post.bookmarked_by?(current_user) %>
              <%= link_to "ブックマークから外す", post_bookmarks_path(post), method: :delete, class: "remove-bookmark gradient" %>
            <% else %>
              <%= link_to "ブックマーク", post_bookmarks_path(post), method: :post, class: "add-bookmark gradient" %>
            <% end %>
          </div>
        <% end %>

        <!--投稿文-->
        <div class="subtitle mt-3 text-center">
          <strong>投稿文</strong>
        </div>
        <div class="post">
          <%= post.introduction %>
        </div>

        <!--コメント欄-->
        <div class="subtitle text-center mt-3">
          <strong>コメント</strong>
          <p>コメント件数：<%= post.comments.with_out_is_deleted.count %>件</p>
        </div>

app/views/admin/posts/index.html.erb
<div class="container">

  <!--検索-->
  <div class="row">
    <div class="col-12 col-md-12 mt-5">
      <div class="mb-2">
        <%= form_with url: admin_posts_path, method: :get, local: true do |f| %>
          <div class="d-flex justify-content-center">
            <i class="fas fa-search fa-lg mt-2 ml-2"></i>
            <%= f.text_field :search, class: "ml-2 mr-2 form-control w-50 border border-dark", value: params[:search], id: "searchBox" %>
            <%= f.submit 'search', class: "search-button btn btn-primary" %>
            <small id="clearSearch" class="clear-button ml-2 btn btn-secondary">クリア</small>
          </div>
        <% end %>
      </div>

      <!--検索ボックスの中をクリアに-->
      <script>
        $('#clearSearch').on('click', (e) => {
          //console.log(e.target)
          $('#searchBox').val("")
        })
      </script>
    </div>
    
    <div class="post-list">
      <div class="row">
        <div class="col-12 col-md-12 d-flex justify-content-start flex-wrap px-0">
          <% @posts.each do |post| %>
            <%= render 'public/users/post', post: post %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<%= render 'showedCal', post: @post, user: @user  %>

        <div class="comment">
          <% @comments.each do |comment|%>
            <div class="border border-dark mx-3 my-4">
              <div class="row mt-2">
                <%= link_to admin_user_path(comment.user.id) do %>
                  <div class="col-1 m-1">
                    <%= image_tag comment.user.get_profile_image(35,35) %>
                  </div>
                  <div class="col-7 d-flex justify-content-start">
                    <%= link_to comment.user.user_name, user_path(comment.user.id), class: "comment-user-name" %>
                  </div>
                <% end %>
              </div>
              <div class="row tb-2 m-2">
                <div class="col-12 comment-sentence mx-1">
                  <%= comment.sentence %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 mt-5 text-center">
      <!--投稿削除-->
      <%= link_to "削除",admin_post_path(@post), method: :delete, class: "btn btn-danger", "data-confirm" => "この投稿を削除しますか？"%>
    </div>
  </div>

</div>