config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /usrs/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# ユーザー
  scope module: :public do
    # homes
    root to: "homes#top"
    get "/privacy"=>"homes#privacy",as: 'privacy'
    get "/help"=>"homes#help",as: 'help'

    # users
    get "/users/my_page"=>"users#my_page",as: 'my_page'
    get "/users/unsubscribe"=>"users#unsubscribe",as: 'unsubscribe'
    patch "/users/withdraw"=>"users#withdraw"
    resources :users, only: [:index, :show, :update, :edit] do
      # relationships
      resource :relationships, only: [:create, :destroy, :follower]
      get "/relationships/following"=>"relationships#following",as: 'following'
      get "/relationships/follower"=>"relationships#follower",as: 'follower'
      # reports
      resources :reports, only: [:new, :create]
    end
    get 'users/:id/reports' => redirect("/users/%{id}/reports/new")
    
    # posts
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      # bookmarks
      resource :bookmarks, only: [:create, :destroy]
      get "/bookmarks/favorite"=>"bookmarks#favorite",as: 'favorite'
    end
    
    # comments
    resources :comments, only: [:create, :destroy]

  end

# 管理者
  namespace :admin do
    root to: "users#index"
  # posts
    resources :posts, only: [:index, :show, :destroy]
  # users
    resources :users, only: [:show, :edit, :update]
  # reports
    resources :reports, only: [:index, :show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord

# user
  belongs_to :reporter, class_name: "User"
  belongs_to :reported, class_name: "User"
  
  validates :reason, presence: true
  
  enum status: { waiting: 0, keep: 1, finish: 2 } 
  
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
# 管理者側  通報
  before_action :authenticate_admin!

  def index
    @reports = Report.all.page(params[:page])
  end

  def show
    @report = Report.find(params[:id])
  end

  # 通報詳細ページで対応ステータス変更
  def update
    @report = Report.find(params[:id])
    @report.update(report_params)
    if @report.reported.is_deleted == true     # もし、通報されたユーザーの退会ステータスが is_deleted == true(退会) だった場合
      @report.update(status: 2)                # 取得したIDの status(対応ステータス) を "2" にアップデート
      # enum status ＝ waiting(対応待ち) → 0    keep(保留中) → 1    finish(対応済み) → 2
    end
    flash[:notice] = "ステータス変更完了"
    redirect_to admin_reports_path
  end

  private

  def report_params
    params.require(:report).permit(:status)
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-md-12 mt-5">
      <h3>
        <strong>通報一覧</strong>
      </h3>
    </div>
  </div>

  <div class="row text-center">
    <div class="col-md-8 report-list mt-3 mx-auto p-0">
      <table class="table table-hover">
        <thead class="table-secondary">
          <tr>
            <th>通報ID</th>
            <th>通報されたユーザー</th>
            <th>対応</th>
            <td><strong>ステータス</strong></td>
          </tr>
        </thead>
        <% @reports.each do |report| %>
          <tbody>
            <tr data-href="/admin/reports/<%= report.id %>">
              <td>
                <%= report.id %>
              </td>
              <td>
                <%= report.reported.user_name %>
              </td>
              <td>
                <%= report.status_i18n %>
              </td>
              <td>
                <% if report.reported.is_deleted == false %>
                  <strong style="color:blue;">有効</strong>
                <% else %>
                  <strong style="color:red;">退会</strong>
                <% end %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center mt-2">
    <%= paginate @reports %>
  </div>
  
  <!--link_to "" do が機能しなかった為、JSで実装-->
  <script>
    $('tr[data-href]').click(function (e) {
      if (!$(e.target).is('a')) {
        window.location = $(e.target).closest('tr').data('href');
      };
    });
  </script>
  
</div>

app/views/admin/reports/show.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col-md-12 mt-2">
      <h3>
        <strong>通報詳細</strong>
      </h3>
    </div>
  </div>
  
  <div class="row mt-1">
    <div class="col-md-6" style="margin: 0 auto;">
      <h5 class="mt-4">
        <strong>通報詳細情報</strong>
      </h5>
      <table class="table">
        <tr>
          <td>通報ID</td>
          <td>
            <%= @report.id %>
          </td>
        </tr>
        <tr>
          <td>通報されたユーザー</td>
          <td>
            <%= link_to @report.reported.user_name, edit_admin_user_path(@report.reported.id) %>
          </td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td>
            <%= form_with model:@report, url:admin_report_path(@report), method: :patch, local: true do |f| %>
              <%= f.select :status, Report.statuses.keys.map { |k| [t("enums.report.status.#{k}"), k] } %>
              <%= f.submit '更新', style: "margin-left:5%;" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  
  <div class="row mt-2">
    <div class="col-md-6 mx-auto">
      <div class="text-center">
        通報者：
        <%= link_to @report.reporter.user_name, admin_user_path(@report.reporter.id) %>
      </div>
      <div>
        <h5>
          <strong>通報理由</strong>
        </h5>
        <div class="admin-report-reason">
          <%= @report.reason %>
        </div>
      </div>
    </div>
    
  </div>
  
</div>