config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /usrs/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions',
  passwords: 'public/passwords'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# ユーザー
  scope module: :public do
    # homes
    root to: "homes#top"
    get "/privacy"=>"homes#privacy",as: 'privacy'
    get "/help"=>"homes#help",as: 'help'

    # users
    get "/users/my_page"=>"users#my_page",as: 'my_page'
    get "/users/unsubscribe"=>"users#unsubscribe",as: 'unsubscribe'
    patch "/users/withdraw"=>"users#withdraw"
    resources :users, only: [:index, :show, :update, :edit] do
      # relationships
      resource :relationships, only: [:create, :destroy, :follower]
      get "/relationships/following"=>"relationships#following",as: 'following'
      get "/relationships/follower"=>"relationships#follower",as: 'follower'
      # reports
      resources :reports, only: [:new, :create]
    end
    get 'users/:id/reports' => redirect("/users/%{id}/reports/new")
    
    # posts
    resources :posts, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      # bookmarks
      resource :bookmarks, only: [:create, :destroy]
      get "/bookmarks/favorite"=>"bookmarks#favorite",as: 'favorite'
    end
    
    # comments
    resources :comments, only: [:create, :destroy]

  end

# 管理者
  namespace :admin do
    root to: "users#index"
  # posts
    resources :posts, only: [:index, :show, :destroy]
  # users
    resources :users, only: [:show, :edit, :update]
  # reports
    resources :reports, only: [:index, :show, :update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>猫の散歩</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/1b0978deee.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <!--ナビゲーション-->
    <style>
      /* overflow を非表示にする */
      html, body {
        overflow-x: hidden;
      }

      /*ページにいるときのcss*/
      nav li {
        border-bottom: 5px solid #555555;
        border-radius: 5px;
      }

      /*aタグを持っている場合*/
      nav li:has(> a) {
        border-bottom: none;
      }

      /*hoverした時のcss*/
      nav li:hover{
        color: #555555;
        border-bottom: 5px solid #EEEEEE;
        border-radius: 5px;
      }

      /*aタグを持っている場合に、hoverした時のcss*/
      nav li:hover > a {
        text-decoration: none;
        color: #EEEEEE;
      }
    </style>
  </head>

  <body>
  <!--Header-->
    <header>
      <div class="container">

        <!--トップロゴ-->
        <div class="row mx-auto">
          <div class="col-md-12 col-sm-12 text-center mt-1">
            <%= link_to "Cat Walk", root_path, class: "logo" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12 mb-2">
            <!--adminのログイン中のHeader-->
            <nav>
              <% if user_signed_in? %>
                <%= image_tag current_user.get_profile_image(70,70), class: "hedder_profile_image" %>
              <% end %>
              <ul>
                <% if admin_signed_in? %>
                  <li>
                    <%= link_to_unless_current "User", admin_root_path %>
                  </li>
                  <li>
                    <%= link_to_unless_current  "Post", admin_posts_path %>
                  </li>
                  <li>
                    <%= link_to_unless_current "Report", admin_reports_path %>
                  </li>
                  <li>
                    <%= link_to_unless_current "Log out", destroy_admin_session_path, method: :delete %>
                  </li>
                <!--publicのログイン中のHeader-->
                <% elsif user_signed_in? %>
                  <li>
                    <%= link_to_unless_current "Post", posts_path %>
                  </li>
                  <li>
                    <%= link_to_unless_current "User", users_path %>
                  </li>
                  <li>
                    <%= link_to_unless_current "My page", my_page_path %>
                  </li>
                <!--ログアウト中のHeader-->
                <% else %>
                  <li>
                    <%= link_to_unless_current "Post", posts_path %>
                  </li>
                  <li>
                    <%= link_to_unless_current "Sign up", new_user_registration_path %>
                  </li>
                  <li>
                    <%= link_to_unless_current "Log in", new_user_session_path %>
                  </li>
                <% end %>
                <!--link_to_unless_current はリンク先が今いるページの場合、aタグをつけない-->
              </ul>
            </nav>
          </div>
        </div>
      </div>

      <!--ヘッダーの猫-->
      <div class="header-cat"></div>

    </header>

  <!--Main-->
    <main style="margin-bottom:50px;">

      <!--成功フラッシュメッセージ-->
      <% if flash[:notice].present? %>
        <div class="alert alert-success text-center">
          <%= flash[:notice] %>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
      <% end %>

      <!--失敗フラッシュメッセージ-->
      <% if flash[:alert].present? %>
        <div class="alert alert-danger text-center">
          <%= flash[:alert].html_safe %>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        </div>
      <% end %>

      <!--ログイン状態の確認-->
      <div class="login_state mt-2">
        <% if user_signed_in? %>
          <%= current_user.user_name %>
        <% elsif admin_signed_in? %>
          <p class="text-danger mt-3">
            管理者ログイン中
          </p>
        <% else %>
          <p class="text-danger mt-3">
            ゲストログイン中
          </p>
        <% end %>
      </div>

      <%= yield %>

    </main>
  <!--Footer-->
    <footer class="border-top border-dark">

      <div class="d-flex justify-content-center">
        <!--プライバシーポリシー-->
        <div class="privacy">
          <%= link_to "Privacy Policy", privacy_path %>
        </div>
        <!--ヘルプ-->
        <div class="help">
          <%= link_to "Help", help_path %>
        </div>
      </div>
      <!--コピーライト-->
      <p class="copyright text-center">
        ©︎️ 2023 Kenta Joko
      </p>

      <!--フッターの猫-->
      <div class="footer-cat"></div>

    </footer>
  </body>
</html>